# OBS代码实战

In [ ]:
import numpy as np

In [2]:
X = np.array([[2, 4, 5], [6, 8, 2]])
W = np.array([[1], [2], [3]])
Y = X @ W
Y

array([[25],
       [28]])

In [3]:
# 定义剪枝的q
w1 = W[0,0]
w1

1

In [5]:
# 计算H
H = X.T @ X
H

array([[40, 56, 22],
       [56, 80, 36],
       [22, 36, 29]])

In [11]:
# 计算H的逆
invH = np.linalg.inv(H + np.eye(len(H)) * 1e-6) # 添加一个数保证数值稳定
invH

array([[ 580498.88133688, -471655.32262675,  145124.69241472],
       [-471655.32262675,  383219.96295623, -117913.84312834],
       [ 145124.69241472, -117913.84312834,   36281.2442488 ]])

In [13]:
e = np.zeros_like(W)
e[0, 0] = 1
deltaW = w1 / invH[0, 0] * invH @ e
deltaW

array([[ 1.        ],
       [-0.81249997],
       [ 0.24999995]])

In [15]:
# 对比剪枝前后
print(f"剪枝前：{(X @ W).tolist()}")
print(f"剪枝后：{(X @ (W-deltaW)).tolist()}")

剪枝前：[[25], [28]]
剪枝后：[[25.000000113281235], [27.999999841796885]]


###  结论：OBS这种方法可以近似获得剪枝前的结果，该方法通过减掉某个权重，然后调整其他的权重值来补偿。